//ACTION TYPES

export const FETCH_POSTS_LIST_REQUEST = "FETCH_POSTS_LIST_REQUEST";
export const FETCH_POSTS_LIST_SUCCESS = "FETCH_POSTS_LIST_SUCCESS";
export const FETCH_POSTS_LIST_FAILURE = "FETCH_POSTS_LIST_FAILURE";
export const FETCH_POSTS_LIST_SKIPPED = "FETCH_POSTS_LIST_SKIPPED";

export const FETCH_COMMENTS_LIST_REQUEST = "FETCH_COMMENTS_LIST_REQUEST";
export const FETCH_COMMENTS_LIST_SUCCESS = "FETCH_COMMENTS_LIST_SUCCESS";
export const FETCH_COMMENTS_LIST_FAILURE = "FETCH_COMMENTS_LIST_FAILURE";

export const ACTION_SELECT_POST = "ACTION_SELECT_POST";

export const ACTION_SET_LIKE_POST = "ACTION_SET_LIKE_POST";
export const ACTION_UNSET_LIKE_POST = "ACTION_UNSET_LIKE_POST";

export const ACTION_SET_LIKE_COMMENT = "ACTION_SET_LIKE_COMMENT";
export const ACTION_UNSET_LIKE_COMMENT = "ACTION_UNSET_LIKE_COMMENT";

//fetch

export const FETCH_PRODUCTS_LIST_REQUEST = "FETCH_PRODUCTS_LIST_REQUEST";
export const FETCH_PRODUCTS_LIST_SUCCESS = "FETCH_PRODUCTS_LIST_SUCCESS";
export const FETCH_PRODUCTS_LIST_FAILURE = "FETCH_PRODUCTS_LIST_FAILURE";
// delete

export const ACTION_DELETE_PRODUCT_REQUEST = "ACTION_DELETE_PRODUCT_REQUEST";
export const ACTION_DELETE_PRODUCT_SUCCESS = "ACTION_DELETE_PRODUCT_SUCCESS";
export const ACTION_DELETE_PRODUCT_FAILURE = "ACTION_DELETE_PRODUCT_FAILURE";

// Create

export const ACTION_CREATE_PRODUCT_REQUEST = "ACTION_CREATE_PRODUCT_REQUEST";
export const ACTION_CREATE_PRODUCT_SUCCESS = "ACTION_CREATE_PRODUCT_SUCCESS";
export const ACTION_CREATE_PRODUCT_FAILURE = "ACTION_CREATE_PRODUCT_FAILURE";
