//fetch

export const FETCH_PRODUCTS_LIST_REQUEST = "FETCH_PRODUCTS_LIST_REQUEST";
export const FETCH_PRODUCTS_LIST_SUCCESS = "FETCH_PRODUCTS_LIST_SUCCESS";
export const FETCH_PRODUCTS_LIST_FAILURE = "FETCH_PRODUCTS_LIST_FAILURE";
// delete

export const ACTION_DELETE_PRODUCT_REQUEST = "ACTION_DELETE_PRODUCT_REQUEST";
export const ACTION_DELETE_PRODUCT_SUCCESS = "ACTION_DELETE_PRODUCT_SUCCESS";
export const ACTION_DELETE_PRODUCT_FAILURE = "ACTION_DELETE_PRODUCT_FAILURE";

// Create

export const ACTION_CREATE_PRODUCT_REQUEST = "ACTION_CREATE_PRODUCT_REQUEST";
export const ACTION_CREATE_PRODUCT_SUCCESS = "ACTION_CREATE_PRODUCT_SUCCESS";
export const ACTION_CREATE_PRODUCT_FAILURE = "ACTION_CREATE_PRODUCT_FAILURE";
